### ISSUE TITLE
prepVol crash due to missing statMap_2D and masks with NaNs

### ISSUE THREAD

**Issue by lydiatgit** [OpenNFT/OpenNFT#10]
(1) OpenNFT crashes in the file prepVol.m if
"if ~isempty(idxActVoxIGLM) && max(tn) > 0 " is not fullfilled due to no activated voxels.
It happens since statMap_2D is not initialised properly outside of the if statement.

(2) If the ROI mask files contains NaNs at the images borders instead of zeros, OpenNFT also crashes in this file.

We made two changes in this file to make it run, please find them in the attached file (sorry, we couldn't attach a .m file) in
Line 348
Line 406-407

[preprVol.txt](https://github.com/OpenNFT/OpenNFT/files/2893393/preprVol.txt)

**Comment by tiborauer** [comment]
Do not you want to submit a PR?

**Comment by da0c** [comment]
We could check and apply your patch, but, it would be great, if you could provide a PR!
https://help.github.com/en/articles/creating-a-pull-request

**Comment by tiborauer** [comment]
I am happy to help you.

**Comment by ykoush** [comment]
Thank you very much for this effort. Please note that I used a bit different fix than you provided. 
1. nans could be more generally fixed in readVol. However, I'd be careful and try to understand why ROIsAnat contained nans in your case. Please remember that wherever this mask is prepared it must be transformed to the individual subjects space using any soft, e.g. SPM, so that it holds identical dimensions and spatial orientation as the EPI template volume for real-time realignment.
2. I mirrored initialization of the statMap2D, i.e. as for the statMap3D.
