### ISSUE TITLE
Issues with shared folder

### ISSUE THREAD

**Issue by aavenka** [OpenNFT/OpenNFT#156]
I'm having an issue with OpenNFT, where if I have nifti files stream into a shared folder and set up OpenNFT to that as the watch folder, it won't notice new nifti images coming in. However, when I do the exact same setup with a local folder, it does update every time a nifti is added to that folder. Do you have any recommendations?

**Comment by ykoush** [comment]
Hi, properly set shared folder works as a local folder for OS. I guess you are using Win PC for that? You can use exactly the same desired folder as a destination for rt export simulation along with openNFT in online mode, using exact the same files without scanner export in rt? I again guess you are using Siemens .dcm export. This would also check if file name and paths are well set.
If your rt export is indeed set and openNFT is working for export simulation, let us know and please provide all the details of your setup.

**Comment by aavenka** [comment]
So we are using a Siemens scanner that is exporting to a windows PC. The PC dicom data is stored in a shared folder that is being monitored by OpenNFT on a Mac that is connected to the shared folder. We see the data successfully transferred to the shared folder and can see it on the Mac, but OpenNFT does not update in real time as the files are being added, it just acts like there are no files in the shared folder.

**Comment by ykoush** [comment]
At some point, I used SAMBA to set the similar setup. I've also heard about an alternative setup, will check. Also, @da0c points to this link: https://stackoverflow.com/questions/45441623/using-watchdog-of-python-to-monitoring-afp-shared-folder-from-linux
We may try to solve it one or another way.

**Comment by da0c** [comment]
This issue probablly caused by a watchdog python package, and the possible solution, accordingly to https://stackoverflow.com/questions/45441623/using-watchdog-of-python-to-monitoring-afp-shared-folder-from-linux is the following.

Change line https://github.com/OpenNFT/OpenNFT/blob/master/opennft/opennft.py#L52  to:
`from watchdog.observers.polling import PollingObserver`

Change line https://github.com/OpenNFT/OpenNFT/blob/master/opennft/opennft.py#L197 to:
`self.fs_observer = PollingObserver()`

So, please, try it, and let us know results.

**Comment by aavenka** [comment]
That worked, thanks! I am having an issue handling .nii.gz files though, I'll open another issue with that problem!

**Comment by ykoush** [comment]
Great!, Reopening since it should be closed with PR from you or @da0c.

**Comment by da0c** [comment]
PollingObserver is a bit more computationally expensive, so I've made it optional, disable by default.
To use it, you need to enable option in config file:
`USE_POLLING_FS_OBSERVER = False`
https://github.com/OpenNFT/OpenNFT/blob/master/opennft/config.py#L67

**Comment by ykoush** [comment]
I'm now wondering if the original problem was caused by watchdog or by .nii.gz rt file extension, and in this regard is just linked to #157. I mean, @aavenka should find out  how the github code they use produces .gz on a Siemens PC side. The easiest could be that @aavenka checks that .gz could be disabled there.
