### ISSUE TITLE
A problem with multiple dcm series in the watch folder

### ISSUE THREAD

**Issue by nitzanlubi** [OpenNFT/OpenNFT#2]
When there are more than one series in the watch folder, the software is delayed for several seconds before loading the data.

**Comment by ykoush** [comment]
Thank you, we'll be working on it. The quickest solution is to leave the watch folder empty (e.g. by moving the acquired data from the folder) when operating in online mode, and with a single series during offline mode.

**Comment by da0c** [comment]
Hello to all,

the problem was in the filename template for search in the folder.
It was just like '*.dcm' instead of something like this -
'001_000007_*.dcm'.
I fixed it, and closed the issue.
So, please, get the last version from github and test it.
Contact me if any problems still present, or better reopen the issue.

Regards,
Artem Nikonorov

2018-07-11 19:20 GMT+04:00 Yury Koush <notifications@github.com>:

**Comment by da0c** [comment]
The problem still present if FirstFileName template is incorrectly configurated.
For example, this misconfig is present in NF_PSC_int_155.ini.

**Comment by da0c** [comment]
I hope, it is now fixed. Test it, please.
