### ISSUE TITLE
Save task parameters

### ISSUE THREAD

**Issue by NinaWie** [OpenNFT/OpenNFT#43]
Hi, I have another question, regarding the P struct: We want to save some values from the ptbTask, for example the reaction times of a subject. We tried to do so by assigning values to P.Task, and then assign P back to the base just as in the example. However, in nfbSave in the end, P.Task does not exist.
We don't understand in detail how the P struct is passed from matlab to python, and why the fields of P change. Do you have an advice how to make sure that P.Task is passed to nfbSave, such that it is saved in the end? Thanks.

**Comment by ykoush** [comment]
The reason for this is probably because you are assigning this P structure variable within PTB process. We call P structures identically within core and PTB processes, however PTB process P structure is called  'ptbP' in core process, just see its usage. 
There are at least 2 possible options:
1) you can save directly from PTB process, check how variable 'eventRecordsPath' is used to store events.
2) you can transfer a variable of P structure form PTB process to core process, then it will appear in the storage.
May be @da0c could advice more on how to transfer such a variable.

**Comment by da0c** [comment]
Yury is right, we have two separate matlab processes, main and ptb, so there are two different P structures.
Here is ptbP initialization code -
https://github.com/OpenNFT/OpenNFT/blob/af9b9d225173c5650abffba271fb28e5e9b0389a/opennft/opennft.py#L1123-L1126
So, you can use the ways proposed by Yury.

Another way, is to access P structure in ptb matlab process is to add code to PtbScreen class (implemented in https://github.com/OpenNFT/OpenNFT/blob/master/opennft/ptbscreen.py).
Inside this class you can access P from python code like this:
```python 
task = self.eng.workspace['P'].Task 
```
or, you can call any matlab routine with access to P from this class.

**Comment by da0c** [comment]
If threre are no more questions, I'll close this issue.
Please, reopen it, if necessary.

**Comment by NinaWie** [comment]
Thanks for your advice, that's very helpful!
