### ISSUE TITLE
MATLAB 2020a

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#76]
Python 3.5 is not suported by MATLAB 2020a. Luckily, python 3.6 is, and OpenNFT work fine on python 3.6. Therefore, I suggest to update README accordingly and allow python 3.6 only.

**Comment by espdev** [comment]
Also we need to support Python >=3.7. Python 3.7 added new keywords async/await, but our code currently does not support it. We need to use `background` argument instead of `async` for calling matlab functions from python asynchronously. 

https://www.mathworks.com/help/matlab/matlab_external/call-matlab-functions-asynchronously-from-python.html
https://www.mathworks.com/help/matlab/apiref/matlab.engine.start_matlab.html#mw_cb7c69ba-b7ff-45dd-a8f7-43ef9ec2a4b6

**Comment by ykoush** [comment]
@espdev if so, how could we keep the support for python 3.7 without loosing 3.5 and 3.6?

**Comment by espdev** [comment]
@ykoush I think we do not need to support Python 3.5 because the modern Python starts from 3.6 version. Also 3.5 version support will be dropped in September, 2020. We can support Python >= 3.6.

**Comment by espdev** [comment]
@ykoush If we support Python >= 3.6 we will need to drop support of MATLAB < R2017b. It is okay?

**Comment by ananthakrishnan-ms** [comment]
Let me learn matlab first

**Comment by ykoush** [comment]
As discussed with @espdev, we will release v1.0.0 after I solve question #59, ending this part of the story. Then we will update core support for Python >= 3.6 and Matlab >2017b.
