### ISSUE TITLE
About setup file

### ISSUE THREAD

**Issue by ptailyyy** [OpenNFT/OpenNFT#8]
1. How can I generate the "SPM_*.mat" file in Settings, does it  saved in psychtoolbox after experiment design? 
2. And which data in "SPM_*.mat" is necessary for OpenNFT? My ".mat" file is different data structure with the demo data.
3. If I want to scan a waterfilm for test，how can I set up the "SPM.mat"?
Thank you very much.

**Comment by ykoush** [comment]
To get started with your OpenNFT Matlab modifications you have to understand the OpenNFT architecture (see the ms about) and which parameters could be set in the functions setupProcParams.m, loadProtocolData.m, nfbInitReward.m, and config.py. The nfbCalc.m function defines the most of the feedback estimation schemes. In addition, get a good understanding on preprVol.m and preprSig.m, since your improper changes of the setup parameters will likely cause errors on data (pre)processing with regular Matlab errors. Check the function captions, since quite a lot of information is provided there. Actively use ctrl+shift+f to track the variable occurrences.

(1) To adopt your paradigm design, you could compare provided feedback types for the set of parameters, and programmed subject interfaces. For some basic changes, such as paradigm timing/blocks, you need to modify existent or create your own data stream under closest feedback type, make your .json file and SPM.mat files, set the logics around contrast (tContr; carefully check the length of vectors on working versions), protocol data, and reward mechanism if applicable. 
To generate the SPM.mat, there is an example batch online: https://github.com/OpenNFT/OpenNFT_Demo/releases/tag/v1.0.
To make/justify your .json files, use loadjson and savejson functions of the jsonlab Matlb toolbox.

(2) There are 3 different types of PTB interfaces implemented (folder nfbDispl). You can implement your own, or modify the already provided. Keep in mind that the debug of PTB-3 functions is a separate Matlab process, which needs to be first enabled (around ‘# Matlab helper process…’ in OpenNFT.py) by replacing with 'desktop' (i.e., before starting OpenNFT.py). This feature opens the Matlab process in a regular desktop mode. Keep in mind that this process is parallel to the Core, i.e. breaking the code in debug mode inside this helper process, will not stop the core process which will continue executing. To avoid such a debug, it is better to have your subject interface ready outside the OpenNFT, and then integrate it. 
Alternatively, you can use your programed interface in an arbitrary software and implement an interaction between it and OpenNFT, e.g. via UDP port (see SVM feedback type example), or any other convenient interaction which you may want to program yourself. 

I'm not sure what do you mean by #3. Otherwise, hope it helps.

**Comment by ptailyyy** [comment]
Thank you for your prompt reply, it is so helpful to me.
