### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#85]
Has anyone tested python 3.8?

Python 3.8 dropped `clock` from module `time`, which causes an issue for pyqtgraph. See also [here](https://forum.learnpyqt.com/t/pyqtgraph-error-module-time-has-no-attribute-clock/99).

I have tried a fresh install, and it crashed with python 3.8 but worked with python 3.7.

**Comment by TheAmid** [comment]
In our installation requirements we set pyqtgraph 0.10.0 due to "NoneType" error ( issue #80 ) which we had with pyqtgraph 0.11.0 (this issue was not fixed in release version, but fixed in master version). In PR #87 we fixed this by referring to master branch. We tested this on python 3.6, 3.7 and 3.8.6.
