### ISSUE TITLE
index exeeds matrix dimensions

### ISSUE THREAD

**Issue by GMAhmadian** [OpenNFT/OpenNFT#9]
Dear all,
I am using opennft in my bachelor end project to display a real-time fMRI dataset from a task ''fingertapping''. after installing opennft, I could run the demo data but when I want to use other datasets, It gives the error that **index exeeds matrix dimenstion**.  even I changed the dimensions of my dataset to the same dimensions of demo data (74x74x36), still problem is the same. 
I woudl appreciat if anyone could help me solve  this probleem.
I was wondering if I could use a 4D or 3D nifti formaat data instead of dicom.
kind regards

**Comment by GMAhmadian** [comment]
![error_opennft](https://user-images.githubusercontent.com/45201062/49098714-d5f9a700-f26f-11e8-85a0-5a2f75d8dea1.JPG)

**Comment by ykoush** [comment]
Hi,
you could double-check if you changed the dimensions properly (i.e. that the header is changed as well), which however you don't really need to do because this is your new project data. It would be better to set OpeNFT for your dataset more carefully, i.e. to make sure that the Template, the ROI(s), and the new dataset have the same dimensions. The easiest is to prepare the new template and new ROIs given your new dataset in SPM. Also, make sure that these new parameters are specified via Review Parameters card and/or in the new setting .ini file.
To get started with some other parameters/changes, please see the comments here: 
https://github.com/OpenNFT/OpenNFT/issues/8

Wrt nifti files, you could use nifti files, which is implemented for Philips scanner with .img extensions, and would require some slight modifications and getting through the logics there. E.g. Phillips 'old' setup did not contain the proper header information for rt export, that is why the current solution was offered.
I suggest that you simply want to run OpenNFT on regular fMRI nifti files, which most likely have the proper header information. So you might want to disable a few steps in the Phillips-related code logic.

**Comment by GMAhmadian** [comment]
thank you for your explanations.
do you have more datasets from the same task and the same subject (with same dimensions as demo data)? so that I could test and compare the results and validate the setup?
