### ISSUE TITLE
Intermittent SVM

### ISSUE THREAD

**Issue by Pamela281** [OpenNFT/OpenNFT#98]
Hello , 

I would like to do intermittent SVM, however I only found a continuous SVM demo. 

Do you have some indications or recommandations to modify existing scripts ? 

Thanks a lot ! 

Pamela

**Comment by ykoush** [comment]
Hi,
the SVM feedback is based on pre-trained classifier (outside OpenNFT), using PRONTO batches and pilot data. You can search for 'SVM' occurrences to understand the pipeline, there are not so many.
The feedback estimation implies a dot product between vectors of data from mask and the weights, which is a very simple operation and could be computed at every scan. The SVM feedback is sent via UDP. 
So, in the simplest case, the intermittent feedback presentation could be implemented on the level of feedback display, i.e. outside OpenNFT. You can add a few commands via UDP to trigger the external software as a function of your paradigm.
If you need to implement the training paradigm of intermittent type, you can see how it is implemented for percent signal change intermittent feedback, ignoring the PTB display.
Otherwise, if you need to inbuilt your entire SVM estimation into the OpenNFT pipeline, you can check the logic behind intermittent PSC and DCM (trail-based) paradigms. In the latter case we can of course guide more.
